# Generated by Django 4.2.1 on 2023-05-06 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prototype", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="taskgroup",
            name="description",
        ),
    ]
